### ISSUE TITLE
Add `ddev-get` topic to help others find addon

### ISSUE THREAD

**Issue by tyler36** [mandrasch/ddev-addon-statamic-please#1]
I recently came across your article, [Setup Statamic via DDEV](https://dev.to/mandrasch/setup-statamic-via-ddev-39bi) article.

I was suprised to see you mention you have an addon.

Please consider adding a `ddev-get` topic to the repo.

This will allow others to find this addon by using: `ddev get --list --all`

## Steps 

1. Click the "cogs" icon 
![cog](https://user-images.githubusercontent.com/7234392/217690357-1eb441fc-6307-46ad-9fea-821d671dd59a.png)

2. Add `ddev-get` as a topic.
![topics](https://user-images.githubusercontent.com/7234392/217690372-0a93c26c-eb11-4f0e-9645-6b9caab301d1.png)

3. Run `ddev get --list --all` and check if "mandrasch/ddev-addon-statamic-please" appears (should appear within a minute).

**Comment by mandrasch** [comment]
Hey @tyler36,

thanks for the info and information!

I added the tag, it can now be found `ddev get --list --all`. 👍 

Just as side note:
If you want to mantain & develop this further, feel free to start an own repository and I'll archive mine + link to yours. Not using statamic currently on a daily basis, just did some tests. But after all it's just the simple command, so I guess there will be no real huge feature requests in future ;-)

 Cheers!

**Comment by tyler36** [comment]
@mandrasch Thanks for adding it!

RE sidenote: 
Thanks for the offer. I've never used Statamic for any "real" projects, just a couple of Laracast videos and such. I think your addon is "feature complete" at the moment so there's really nothing more to do. 

Cheers!
