### ISSUE TITLE
Pretty simple! But please add tests, update "maintained" badge

### ISSUE THREAD

**Issue by rfay** [mandrasch/ddev-addon-statamic-please#3]
Hi @mandrasch - I'm doing an inventory of add-ons. This one is discoverable because of the "ddev-get" topic on it. Maybe you don't want it to be. And it has no automated tests (you probably don't think it needs any)

But please consider:
* Removing the "ddev-get" topic from the repo if it's not for public use
* Adding automated tests per the ddev-addon-template
* Updating the "maintained" badge in the readme.

Thanks!

**Comment by mandrasch** [comment]
Removed "ddev-get" 👍
